- name: Variable PLAY
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Enter your USERNAME
    private: false
  - name: PASSWORD
    prompt: Enter your password
    private: true
  
  tasks:
  - name: Task 1
    vars:
      surname: "GOTTAM"
      lastname: "REDDY"
    ansible.builtin.debug:
      msg: "my name is {{surname}} {{lastname}} // {{USERNAME}}  {{PASSWORD}}"

- name: Datatypes
  hosts: localhost
  vars:
    age: 20
    sex: "male"
    skills:
    - DevOps
    - AWS
    Experience:
      DevOps: 3
      AWS: 4
  tasks:
  - name: Task 1
    ansible.builtin.debug:
      msg: "skills ans experice is  {{skills}} {{Experience}}"
      
      