- name: Variable PLAY
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Enter your USERNAME
    private: false
  - name: PASSWORD
    prompt: Enter your password
    private: true
  
  tasks:
  - name: Task 1
    vars:
      surname: "GOTTAM"
      lastname: "REDDY"
    ansible.builtin.debug:
      msg: "my name is {{surname}} {{lastname}} // {{USERNAME}}  {{PASSWORD}}"
      