- name: User PlayBook
  become: yes
  hosts: user 
  tasks:
  - name: Disable, enable 18 and install nodejs PLAY
    ansible.builtin.shell: dnf module disable nodejs -y ;dnf module enable nodejs:18 -y 
    
  - name: Installing nodejs PlayBook
    ansible.builtin.package: 
      name: nodejs
      state: present

  - name: Getting user details PLAY
    ansible.builtin.shell: id roboshop
    register: userdetails
    ignore_errors: True

  - name: Printing error 
    ansible.builtin.debug:
      msg: "user not found so creating"

  - name: Add the user 'roboshop' PLAY
    ansible.builtin.user:
      name: "roboshop"
      comment: John Doe
    when: userdetails.rc != 0

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory
      mode: '0777'
  - name: Download foo.conf
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp/user.zip
  
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: npm install
    ansible.builtin.command:  npm install
    args:
      chdir: /app

  - name: Copy file  user side
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
  
  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      daemon_reload: true
      
  - name: Copy file  mongo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing nodejs PlayBook
    ansible.builtin.package: 
      name:  mongodb-org-shell
      state: present
  - name: get the users count
    ansible.builtin.command:  mongo --host 172.31.43.84 --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{product_count}}"

  - name: load user data
    ansible.builtin.command: mongo --host 172.31.43.84 < /app/schema/user.js
    when: product_count.stdout == "0" # keep double quotes

   
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes
