- name: WEB Installing PLAYBOOK
  become: yes
  hosts: web
  tasks:
    - name: Install web application
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent

    - name: Download web application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp/web.zip

    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy file to remote
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
