- name: Installing catalogue
  hosts: catalouge
  become: yes
  tasks:
   - name: Installing mongodb
     ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
   - name: Install ntpdate
     ansible.builtin.package:
        name: nodejs
        state: present
   - name: Installing mongodb
     ansible.builtin.command: id roboshop
     register: output
   - name: printing output
     ansible.builtin.debug:
      msg: "op is {{output}}"
   

